// Generated by CoffeeScript 1.10.0
(function() {
  var Reader;

  Reader = (function() {
    function Reader() {
      this.keyPresses = [];
      this.lastTimeStamp = 0;
    }

    Reader.prototype.addKey = function(keyString, time) {
      if (time - this.lastTimeStamp < 25) {
        this.keyPresses[this.keyPresses.length - 1][0] += keyString;
      } else {
        this.keyPresses.push([keyString, time]);
      }
      return this.lastTimeStamp = time;
    };

    Reader.prototype.toHTML = function() {
      return this.keyPresses.join("<br>");
    };

    return Reader;

  })();

  $(function() {
    var printing, reader;
    $('#clearButton').click(function() {
      return $('#test').empty();
    });
    printing = false;
    reader = new Reader();
    return $(document).keypress(function(e) {
      var key, keyCode, time;
      keyCode = e.which;
      time = e.timeStamp;
      if (keyCode === 223) {
        printing = !printing;
        if (printing === false) {
          $('#test').append(reader.toHTML());
        }
        return console.log("printing is now " + (printing ? "on" : "off"));
      } else if (printing) {
        key = String.fromCharCode(keyCode);
        console.log(key + " = " + keyCode + " at " + time);
        return reader.addKey(key, time);
      }
    });
  });

}).call(this);
