// Generated by CoffeeScript 1.10.0
(function() {
  var Reader;

  Reader = (function() {
    function Reader() {
      this.keyPresses = [];
      this.lastKeyPress = "";
      this.lastTimeStamp = 0;
    }

    Reader.prototype.addKeyPress = function(keyString, time) {
      var diff;
      if (time - this.lastTimeStamp < 25) {
        this.keyPresses[this.keyPresses.length - 1][0] += keyString;
      } else {
        diff = this.lastTimeStamp === 0 ? 0 : time - this.lastTimeStamp;
        if (this.lastKeyPress) {
          this.keyPresses.push([this.lastKeyPress, diff]);
        }
      }
      this.lastTimeStamp = time;
      return this.lastKeyPress = keyString;
    };

    Reader.prototype.toHTML = function() {
      return this.keyPresses.join("<br>");
    };

    return Reader;

  })();

  $(function() {
    var clearFunc, printing;
    clearFunc = (function(_this) {
      return function() {
        $('#test').empty();
        return _this.reader = new Reader();
      };
    })(this);
    printing = false;
    this.reader = new Reader();
    $(document).keypress(function(e) {
      var key, keyCode, time;
      keyCode = e.which;
      time = e.timeStamp;
      if (keyCode === 223) {
        printing = !printing;
        if (printing === false) {
          $('#test').append(this.reader.toHTML());
        }
        return console.log("printing is now " + (printing ? "on" : "off"));
      } else if (printing) {
        key = String.fromCharCode(keyCode);
        console.log(key + " = " + keyCode + " at " + time);
        return this.reader.addKeyPress(key, time);
      } else if (keyCode === 12) {
        return clearFunc();
      }
    });
    return $('#clearButton').click(clearFunc);
  });

}).call(this);
